       IDENTIFICATION DIVISION.
       PROGRAM-ID. DOOM-COBOL.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-MSG PIC X(30) VALUE "DOOM COBOL - ENGINE STARTING".

       PROCEDURE DIVISION.
           DISPLAY WS-MSG
           STOP RUN.
